FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("openstack/rally", "/rally") }}
{{ copy_sources("openstack/tempest", "/tempest") }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssh-client \
    && apt-get clean \
    && useradd --user-group --create-home --home-dir /var/lib/rally rally \
    && chmod 755 /var/lib/rally \
    && usermod -a -G microservices rally \
    && /var/lib/microservices/venv/bin/pip install /rally \
    && rm -fr /rally \
    && mv /tempest /var/lib/rally/tempest

COPY mitaka-skip-list.list /var/lib/rally/
COPY newton-skip-list.list /var/lib/rally/
COPY ocata-skip-list.list /var/lib/rally/
COPY check_status.py /var/lib/rally/

RUN chown -R rally: /var/lib/rally \
    && chmod 755 /var/lib/rally/check_status.py

USER rally
WORKDIR /var/lib/rally
